### ISSUE TITLE
Gstreamer version discrepancy in rel-2020.1 and rel-2020.2

### ISSUE THREAD

**Issue by dtrussel** [Xilinx/meta-petalinux#16]
When checking the bbappends for the gstreamer recipes i realized that the version is set to [1.16.0](https://github.com/Xilinx/meta-petalinux/blob/rel-v2020.1/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_%25.bbappend#L6)
However in the gstreamer mirror repos of xilinx itself it says it is release [1.16.1](https://github.com/Xilinx/gst-plugins-base/blob/release-2020.1/RELEASE#L1)
And on the poky zeus release it is version 1.16.2.
Seems a bit messy. Which version is the one really targeted with the xilinx 2020.1 release?

**Comment by dtrussel** [comment]
A bit disappointing that this problem is still the same in the 2020.2 release and this issue not even got an answer since June...

**Comment by ckalluri73** [comment]
Hi, for 2020.1 and 2020.2 the xilinx gstreamer versions are set to 1.16.1. Thank you for pointing out the issue with PV. We will update it in our next release.

**Comment by dtrussel** [comment]
Great news, thank you for your time.
