### ISSUE TITLE
Can't build petalinux-image-full for zcu102-zynqmp

### ISSUE THREAD

**Issue by brunosmmm** [Xilinx/meta-petalinux#2]
When trying to build (using Yocto distribution fetched using github.com/Xilinx/yocto-manifests), 2017.4 building **xen** fails with: 

```
WARNING: xen-4.8.0-r0 do_fetch: Failed to fetch URL git://github.com/Xilinx/xen.git;protocol=https;branch=xilinx/stable-4.8, attempting MIRRORS if available                                                       
ERROR: xen-4.8.0-r0 do_fetch: Fetcher failure: Unable to find revision 75c00aca503fe7093ccfecb3d0dd803642cb7bae in branch xilinx/stable-4.8 even from upstream                                                     
ERROR: xen-4.8.0-r0 do_fetch: Fetcher failure for URL: 'git://github.com/Xilinx/xen.git;protocol=https;branch=xilinx/stable-4.8'. Unable to fetch URL from any source.                                             
ERROR: xen-4.8.0-r0 do_fetch: Function failed: base_do_fetch
```

Upon further inspection, the commit *75c00aca503fe7093ccfecb3d0dd803642cb7bae* does not belong to any branch in the tree. It is tagged as **rel-v2017.4** which makes sense as to why this revision would be selected in the **rel-v2017.4** branch of meta-petalinux. (I am avoiding 2018.1 for now)

Temporarily fixed it by using the latest commit in the upstream branch, however this is pretty annoying.

**Comment by mharth** [comment]
Saw this now, I think Xen tree got overwritten somehow which is unfortunate. You can set BRANCH = "" as workaround (BRANCH_pn-xen = ""  in local.conf) 
This will ensure nobranch=1 is used and will search the entire tree

**Comment by mharth** [comment]
https://github.com/Xilinx/meta-petalinux/blob/master/recipes-extended/xen/xen_git.bbappend#L4
