### ISSUE TITLE
ERROR: petalinux-user-image-1.0-r0 do_rootfs: The postinstall intercept hook 'update_icon_cache' failed

### ISSUE THREAD

**Issue by pedrombmachado** [Xilinx/meta-petalinux#9]
Dear all,

 I am getting the following error when running petalinux-build on Petalinux 2019.1 running on Ubuntu 18.04 LTS:

> ERROR: petalinux-user-image-1.0-r0 do_rootfs: The postinstall intercept hook 'update_icon_cache' failed, details in /media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/build/tmp/work/plnx_zynqmp-xilinx-linux/petalinux-user-image/1.0-r0/temp/log.do_rootfs
> ERROR: petalinux-user-image-1.0-r0 do_rootfs: Function failed: do_rootfs
> ERROR: Logfile of failure stored in: /media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/build/tmp/work/plnx_zynqmp-xilinx-linux/petalinux-user-image/1.0-r0/temp/log.do_rootfs.7604
> ERROR: Task (/media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/project-spec/meta-plnx-generated/recipes-core/images/petalinux-user-image.bb:do_rootfs) failed with exit code '1'
> 
> 

`$ cat /media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/build/tmp/work/plnx_zynqmp-xilinx-linux/petalinux-user-image/1.0-r0/temp/log.do_rootfs`

> NOTE: Running /media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/build/tmp/work/plnx_zynqmp-xilinx-linux/petalinux-user-image/1.0-r0/recipe-sysroot-native/usr/bin/dnf -v --rpmverbosity=debug -y -c /media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/build/tmp/work/plnx_zynqmp-xilinx-linux/petalinux-user-image/1.0-r0/rootfs/etc/dnf/dnf.conf --setopt=reposdir=/media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/build/tmp/work/plnx_zynqmp-xilinx-linux/petalinux-user-image/1.0-r0/rootfs/etc/yum.repos.d --repofrompath=oe-repo,/media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/build/tmp/work/plnx_zynqmp-xilinx-linux/petalinux-user-image/1.0-r0/oe-rootfs-repo --installroot=/media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/build/tmp/work/plnx_zynqmp-xilinx-linux/petalinux-user-image/1.0-r0/rootfs --setopt=logdir=/media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/build/tmp/work/plnx_zynqmp-xilinx-linux/petalinux-user-image/1.0-r0/temp repoquery --installed --queryformat Package: %{name} %{arch} %{version} %{name}-%{version}-%{release}.%{arch}.rpm
> Dependencies:
> %{requires}
> Recommendations:
> %{recommends}
> DependenciesEndHere:
> 
> NOTE: Installing complementary packages ...
> NOTE: Running ['oe-pkgdata-util', '-p', '/media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/build/tmp/pkgdata/plnx-zynqmp', 'glob', '/tmp/installed-pkgsp2s98wr8', '']
> NOTE: Running intercept scripts:
> NOTE: > Executing update_icon_cache intercept ...
> NOTE: Exit code 127. Output:
> /media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/build/tmp/work/plnx_zynqmp-xilinx-linux/petalinux-user-image/1.0-r0/intercept_scripts-c972dfd7f61e41279b1ea6467ddf3eeb0fa368dddd1f641e88cb83712a33f996/update_icon_cache: line 6: /media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/build/tmp/work/plnx_zynqmp-xilinx-linux/petalinux-user-image/1.0-r0/recipe-sysroot-native//gdk-pixbuf-2.0/gdk-pixbuf-query-loaders: No such file or directory
> 
> ERROR: The postinstall intercept hook 'update_icon_cache' failed, details in /media/pedro/OS/Xilinx/petalinux/Builds/2019.1/ZU4EV/build/tmp/work/plnx_zynqmp-xilinx-linux/petalinux-user-image/1.0-r0/temp/log.do_rootfs
> DEBUG: Python function do_rootfs finished
> ERROR: Function failed: do_rootfs

The project compiles fine on Petalinuz 2019.1 running on Ubuntu 16.04 LTS. It is said thon the Petalinux 2019.1 documentation that it is compatible with Ubuntu 18.04 LTS.

Also reported [here](https://forums.xilinx.com/t5/Embedded-Linux/ERROR-petalinux-user-image-1-0-r0-do-rootfs-The-postinstall/td-p/1026150)

**Comment by VitaliyKRS** [comment]
@pedrombmachado Did you fix this error?

**Comment by pedrombmachado** [comment]
yes I did. I had to re-install petalinux in /petalinux because the name of the folders has very long.
